language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test
  - yarn build
# deploy:
#   provider: surge
#   skip_cleanup: true
#   domain: <my_name_here>.surge.sh
#   project: ./build/
# on:
#   branch: master